
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --

#include <cdk/ast/all.h>


#ifdef __NODE_DECLARATIONS_ONLY__

namespace l22 {

class address_of_node;
class again_node;
class block_node;
class evaluation_node;
class function_call_node;
class function_definition_node;
class identity_node;
class if_else_node;
class if_node;
class index_node;
class input_node;
class nullptr_node;
class program_node;
class return_node;
class sizeof_node;
class stack_alloc_node;
class stop_node;
class variable_declaration_node;
class while_node;
class write_node;


} // namespace l22

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_l22_NODE_ALL_NODES_H__
#define __AUTOMATIC_l22_NODE_ALL_NODES_H__

#include "ast/address_of_node.h"
#include "ast/again_node.h"
#include "ast/block_node.h"
#include "ast/evaluation_node.h"
#include "ast/function_call_node.h"
#include "ast/function_definition_node.h"
#include "ast/identity_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/index_node.h"
#include "ast/input_node.h"
#include "ast/nullptr_node.h"
#include "ast/program_node.h"
#include "ast/return_node.h"
#include "ast/sizeof_node.h"
#include "ast/stack_alloc_node.h"
#include "ast/stop_node.h"
#include "ast/variable_declaration_node.h"
#include "ast/while_node.h"
#include "ast/write_node.h"


#endif /* !defined(__AUTOMATIC_l22_NODE_ALL_NODES_H__) */
#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

