
//-- AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT --
#include <cdk/ast/visitor_decls.h>

#ifdef __IN_VISITOR_HEADER__
#ifdef __PURE_VIRTUAL_DECLARATIONS_ONLY__
  virtual void do_address_of_node(l22::address_of_node *const node, int lvl) = 0;
  virtual void do_again_node(l22::again_node *const node, int lvl) = 0;
  virtual void do_block_node(l22::block_node *const node, int lvl) = 0;
  virtual void do_evaluation_node(l22::evaluation_node *const node, int lvl) = 0;
  virtual void do_function_call_node(l22::function_call_node *const node, int lvl) = 0;
  virtual void do_function_definition_node(l22::function_definition_node *const node, int lvl) = 0;
  virtual void do_identity_node(l22::identity_node *const node, int lvl) = 0;
  virtual void do_if_else_node(l22::if_else_node *const node, int lvl) = 0;
  virtual void do_if_node(l22::if_node *const node, int lvl) = 0;
  virtual void do_index_node(l22::index_node *const node, int lvl) = 0;
  virtual void do_input_node(l22::input_node *const node, int lvl) = 0;
  virtual void do_nullptr_node(l22::nullptr_node *const node, int lvl) = 0;
  virtual void do_program_node(l22::program_node *const node, int lvl) = 0;
  virtual void do_return_node(l22::return_node *const node, int lvl) = 0;
  virtual void do_sizeof_node(l22::sizeof_node *const node, int lvl) = 0;
  virtual void do_stack_alloc_node(l22::stack_alloc_node *const node, int lvl) = 0;
  virtual void do_stop_node(l22::stop_node *const node, int lvl) = 0;
  virtual void do_variable_declaration_node(l22::variable_declaration_node *const node, int lvl) = 0;
  virtual void do_while_node(l22::while_node *const node, int lvl) = 0;
  virtual void do_write_node(l22::write_node *const node, int lvl) = 0;

#else
  void do_address_of_node(l22::address_of_node *const node, int lvl);
  void do_again_node(l22::again_node *const node, int lvl);
  void do_block_node(l22::block_node *const node, int lvl);
  void do_evaluation_node(l22::evaluation_node *const node, int lvl);
  void do_function_call_node(l22::function_call_node *const node, int lvl);
  void do_function_definition_node(l22::function_definition_node *const node, int lvl);
  void do_identity_node(l22::identity_node *const node, int lvl);
  void do_if_else_node(l22::if_else_node *const node, int lvl);
  void do_if_node(l22::if_node *const node, int lvl);
  void do_index_node(l22::index_node *const node, int lvl);
  void do_input_node(l22::input_node *const node, int lvl);
  void do_nullptr_node(l22::nullptr_node *const node, int lvl);
  void do_program_node(l22::program_node *const node, int lvl);
  void do_return_node(l22::return_node *const node, int lvl);
  void do_sizeof_node(l22::sizeof_node *const node, int lvl);
  void do_stack_alloc_node(l22::stack_alloc_node *const node, int lvl);
  void do_stop_node(l22::stop_node *const node, int lvl);
  void do_variable_declaration_node(l22::variable_declaration_node *const node, int lvl);
  void do_while_node(l22::while_node *const node, int lvl);
  void do_write_node(l22::write_node *const node, int lvl);

#endif /* !defined(__PURE_VIRTUAL_DECLARATIONS_ONLY__) */
#endif /* __IN_VISITOR_HEADER__ */

