
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace fir {

class addressof_node;
class alloc_node;
class block_node;
class body_node;
class evaluation_node;
class func_call_node;
class func_decl_node;
class func_def_node;
class if_else_node;
class if_node;
class index_node;
class leave_node;
class nullptr_node;
class pos_node;
class print_node;
class read_node;
class restart_node;
class return_node;
class sizeof_node;
class var_decl_node;
class while_node;


} // namespace fir

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_fir_NODE_ALLNODES_H__
#define __AUTOMATIC_fir_NODE_ALLNODES_H__

#include "ast/addressof_node.h"
#include "ast/alloc_node.h"
#include "ast/block_node.h"
#include "ast/body_node.h"
#include "ast/evaluation_node.h"
#include "ast/func_call_node.h"
#include "ast/func_decl_node.h"
#include "ast/func_def_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/index_node.h"
#include "ast/leave_node.h"
#include "ast/nullptr_node.h"
#include "ast/pos_node.h"
#include "ast/print_node.h"
#include "ast/read_node.h"
#include "ast/restart_node.h"
#include "ast/return_node.h"
#include "ast/sizeof_node.h"
#include "ast/var_decl_node.h"
#include "ast/while_node.h"


#endif /* !defined(__AUTOMATIC_fir_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

